#!/bin/bash

# Ask the user for the name of the script
read -p "Enter the name of the script: " script_name
read -p "Enter pathname:" path

# Create the file with the given name and add a shebang line
touch "./$path/$script_name"
echo "
#include <stdio.h>

/**
 * main - Entry point for the program
 *
 * Return: Always 0 (Success)
 */
int main(void)
{
	/* Your code here */
	return (0);
}

" > "./$path/$script_name"

# Open the file in the default text editor
vi "./$path/$script_name"
